# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24459f83d05b4a2e970d23e7f0bd936f8a179d908a6dfbc05f0d3eaef582e1824205b6dacdbeea23f919c37e831d34fd50a157c64ef5434a9c818d548b015369

test:
  secret_key_base: 74fcdfb7da305107e4a72024c084102a318ee83f9b15f99fdf598a63ee4d0b43c701c80759c8e8c70b64b9495383c73a7c5e34e8e0e77c7cd8e4ab9ca2192f23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
